### ISSUE TITLE
Question: How do I get list of organizations a user is associated to

### ISSUE THREAD

**Issue by purimetla** [octokit/plugin-enterprise-server.js#99]
Hey,
I'm using Github Enterprise and my use case is to get metrics using GitHub API. As part of this effort, I've a list of users to go against and fetch the necessary data for reporting and analysis.

I'm trying to get all the Organizations(public & private) each user belongs to and get all repositories within those organizations and get stats for each repository.

I tried using this method: octokit.orgs.listForUser({ username, per_page, page }); which results in only public orgs. Since it is enterprise GitHub server, all orgs are private and I'm unable user organizations.

Can you recommend/suggest if there is a way to fetch this data.

P.S: There seems to be an GitHub endpoint for this ask but this is only for an authenticated user.
https://developer.github.com/enterprise/2.20/v3/orgs/#list-your-organizations

**Comment by gr2m** [comment]
The endpoint used for `octokit.orgs.listForUser({ username, per_page, page })` is https://developer.github.com/v3/orgs/#list-user-organizations. The description states that the endpoint returns only the public memberships

> List public organization memberships for the specified user

In order to get all organizations a user is associated with, you need to authenticate as that user, as far as I know.

Maybe there is an enterprise-only endpoint that can be used that I'm not aware of. Could you ask support about it? https://enterprise.githubsupport.com/hc/en-us/requests/new

**Comment by purimetla** [comment]
@gr2m 

Thanks for your input and pointing me in the right direction. I've just submitted a request asking the same.

Regards
Anil

**Comment by gr2m** [comment]
I'll close the issue for the time being as there is nothing actionable for me right now, but please let me know what support says, and reopen the issue if there is something I can help with from my side
